version: "3"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1StrongPassword!"
      ACCEPT_EULA: "Y"
  dotquiz.api:
    image: ${DOCKER_REGISTRY-}dotnet
    ports:
      - 49838:443
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - sql-server-db
